[package]
name = "quickfolder"
version = "0.0.1"
edition = "2024"
rust-version = "1.92"
description = "A lightweight Windows folder launcher"
license = "MIT"
repository = "https://github.com/yorelll/quickfolder"
readme = "README.md"
publish = false
build = "build.rs"

[features]
default = []

[dependencies]
slint = { version = "=1.18.0", default-features = false, features = [
    "std",
    "compat-1-2",
    "backend-winit",
    "renderer-software",
    "software-renderer-systemfonts",
    "accessibility",
    "system-tray",
] }

[build-dependencies]
slint-build = "=1.18.0"
winresource = "=0.1.31"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
